name: CI

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Upgrade
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

env:
  CI: true
  NODE_ENV: development

defaults:
  run:
    shell: bash

jobs:
  test:
    name: CI for Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node:
          - lts/hydrogen
          - lts/iron
          - current
        os:
          - ubuntu-22.04
          - macos-14
          - windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Try format
        run: npm run format

      - name: Try lint
        run: npm run lint

      - name: Try build
        run: npm run build

      - name: Run tests
        run: npm test -- --reporter=junit --outputFile=./reports/jest-junit.xml

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests for Node.js ${{ matrix.node }} on ${{ matrix.os }}
          path: reports/jest-*.xml
          reporter: jest-junit
